import Head from 'next/head'
import Link from 'next/link';
import { FEEDS } from './api/rss';
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Crisp Wave</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div>
            <h1>Crisp Waves</h1>
            <div>
              {FEEDS.map((feed) => (
                <Link key={feed.slug} href={`/feeds/${feed.slug}`}>
                  {feed.title}
                </Link>
              ))}
            </div>
          </div>
        </main>
    </>
  )
}
